### ISSUE TITLE
Multipla Caja instances During  Startup

### ISSUE THREAD

**Issue by willysr** [mate-desktop/caja#100]
When logging in to MATE Desktop on some environments, caja may runs multiple times without any ability to being stopped unless it reached the open process limit

Adding --sync to caja.desktop solved this problem

**Comment by Hyperion1337** [comment]
I had this issue with a fresh install of Ubuntu Mate 64bit 16.4 LTS caused by "antivirus" from the "welcome" software. It is a gui front end for clamAV. The caja add-on is the problem. Once I uninsulated the front end "antivirus" it stopped happening.

**Comment by allanlaal** [comment]
issue persists in caja 1.24.0-1 on Ubuntu 20.04 nightly

**Comment by mperezrueda** [comment]
> issue persists in caja 1.24.0-1 on Ubuntu 20.04 nightly

Yes,same issue

**Comment by yledoare** [comment]
Fixed for the next LinuxConsole release
https://bitbucket.org/yourdistrofromscratch/ydfs/src/46090263a70fbd70a672df20412a75e396414b40/2.8/packages/patches/caja-1.24.0.diff

**Comment by HowardRubin-dev** [comment]
As of January 20, 2021, this is still an issue in caja 1.24.0 on Ubuntu Mate with the latest updates and:
X-MATE-AutoRestart=false

$ uname -a
Linux h1 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
