### ISSUE TITLE
The location is not a folder - Google Chrome

### ISSUE THREAD

**Issue by brown-d** [mate-desktop/caja#1536]
#### Expected behaviour
I click 'Show in folder' in the 'Downloads' interface of Google Chrome. Caja opens to the relevant folder with that file highlighted. This works fine in Nautilus.

#### Actual behaviour
Caja opens to my home folder and pops up an error window indicating, "The location is not a folder."

#### Steps to reproduce the behaviour
Download a file in google chrome. Hit ctrl+j for 'downloads' interface. Click the 'Show in folder' link for the downloaded file.
![caja_error](https://user-images.githubusercontent.com/5743607/124006755-7d429b80-d98f-11eb-8d08-a9532cc064f6.png)

#### MATE general version
mate-desktop 1.24.0-2
mate-desktop-common 1.24.0-2
mate-user-guide 1.24.0-1 

#### Package version
1.24.0-1

#### Linux Distribution
Ubuntu 20.04.2 with Unity-desktop (NOT MATE).

**Comment by lukefromdc** [comment]
This looks like Chrome is successfully invoking caja, but passing the filename of the downloaded item to caja rather than the name of the directory containing the file. Thus, this becomes the EXPECTED behavior of Caja if that's what Chrome (which I do not have installed) is asking it to do.  If you type `caja ` in terminal, and then drag and drop any file (not a directory) onto the terminal and hit return, you will see exactly the same behavior: the "location is not a folder" dialog, coming up as caja opens directories not files.

Nemo and Nautilus by comparison DO automatically open the parent directory of any file they are asked to open, with that file selected. Not sure whether that was ever the case in Nautilus in GNOME 2 (and later broken), was a feature added to Nautilus somewhere between the initial port to GTK3 for Nautilus 3.0 and Nautilus 3.4, which was forked to become Nemo, or was added to Nautilus still later and then ported to Nemo.

**Comment by brown-d** [comment]
Same happens with Firefox.

FYI Firefox version 90.0 64-bit (ubuntu package "90.0+build1-0ubuntu0.20.04.1").

**Comment by lukefromdc** [comment]
That is no surprise: Caja does not currently support opening with a file as an argument, only with a directory as an argument. Browsers are trying to pass the filename, not the directory name to Caja, as this works with Nautilus and Nemo. I do not know when that was added to them, or if Nautilus 2/Caja once had this feature and it broke or got left behind in a code migration.

**Comment by brown-d** [comment]
The code seems to be from 10 years ago, if I'm reading this correctly.
[https://github.com/mate-desktop/caja/blame/2c823efff95a07ac10948a6fcfd0fc05fe0fcd58/src/caja-window-manage-views.c#L2153](https://github.com/mate-desktop/caja/blame/2c823efff95a07ac10948a6fcfd0fc05fe0fcd58/src/caja-window-manage-views.c#L2153)

**Comment by lukefromdc** [comment]
That code is simply the error message handling for when caja is given a non-file URL. Finding out when this was REMOVED from nautilus or nemo would find the commit there where this was fixed

**Comment by brown-d** [comment]
The code in question is still present in Nautilus, but doesn't get called in this situation. Here is a link to the function used to 'give' nautilus the parent folder so that the 'not a folder' error can be avoided. This is the oldest reference to this function that I can find on the Nautilus github and it appears it was added as a 'cleaning' commit? Maybe some Nautilus history is missing.

https://github.com/GNOME/nautilus/blame/3c66ac706569583c1c9adb9cb0f2e94a1a47ea77/src/nautilus-window-slot.c#L1258

**Comment by thedanyes** [comment]
I can't imagine that everyone using the MATE Desktop with it's default file browser is subject to this same issue. Clicking the browser's 'show in folder' is not some isolated niche use case. Can anyone else replicate the issue from Chrome or Firefox?

**Comment by lukefromdc** [comment]
Did you have something opening in browser at startup? If so we may need to document that doing
so is broken for now

**Comment by ArcticWolfSS82** [comment]
I did not have any browser, browser-based app or caja open on system startup.
I don't think this is related to the login issue I was having ― that appears to be an `Arctica greeter` issue. The bug I listed matches the behavior I was seeing exactly.

The issue with caja I'm experiencing occurs in the same way as initially reported:

1. Open any browser
2. Download a file or web page of any kind
3. Click the folder icon to open in directory
4. Get error "The location is not a folder" when `caja` is set as the preferred file manager for the system.
5. Switch preferred file manager to a different application, like nemo
6. Click folder icon to open in directory
7. Configured file manager opens to directory (expected behavior)

**Comment by lukefromdc** [comment]
As of now, from inside Firefox or Librewolf, "show in folder" from the browser's downloads>show all download window actually does work, at least when running from the wayland session. I have caja, nemo, and nautilus all installed, caja set in the control center preferred applications cappet as the system browser.

I have no idea if this works in Chrome as I do not use Google's products myself.

**Comment by lukefromdc** [comment]
I am using a local build from git master (now on 1.29). Ubuntu is still on 1.26 and has been since before 24.04 was released. This implies the problem came in either with something in one of the two newer builds of caja 1.26 by Ubuntu or possibly something outside caja itself that changed between 24004 and 24.10/
