### ISSUE TITLE
White text on white page, icon view.

### ISSUE THREAD

**Issue by caz747** [mate-desktop/caja#381]
I'm not currently using Mate 17.1, I switched back to Mate 17, due to the problem I was having with the icon view in my home folder. 
Using any theme, other than the Mint X themes, would cause the text below the icons to be displayed in white, even though the theme stated that it used  black as a font colour. On a white page this was pretty unusable. 
The last time I used Mate 17.1, a few weeks ago, the only themes that would display the text in the correct black colour were all of the Mint-X- themes that are available via Appearance Preferences. 
In the Customise Theme section under the Controls tab all of the Mint-X- themes display the text as black, but if I switched to any of the other pre-installed themes that come with Mint 17.1, and try to use them for the controls settings then the text below the icons turns white 
The only exception I could find among the pre-installed themes, where the text colour was black as it should be, and is stated as being, was the Thinice theme.
 
I have no idea as to why the ThinIce theme behaves correctly and the others don't but that's how things were working the last time I used 17.1

Bit of a delay in me reporting this, I fixed the issue by switching back to Mint 17 and forgot about the problem, thought it worth mentioning though so it can be looked at for future releases.

**Comment by NiceandGently** [comment]
Do you use a a solid background?

**Comment by caz747** [comment]
Yes, at the time when I was running Mint 17.1 it was a solid colour for the background inside my Home folder, a plain white background. On the Desktop there was a photo which was mostly dark in colour. The fonts below the desktop icons were visible, but this was because they were white in colour and the desktop background was dark, unlike the solid white colour used in my Home folder.

Here's a link to the original thread I posted over at the Linux Mint forum http://forums.linuxmint.com/viewtopic.php?f=206&t=185256  
It might be of some help.

**Comment by NiceandGently** [comment]
This is fixed since a long time and released with caja-1.8.2.
https://github.com/mate-desktop/caja/commit/c5b6013dd50e5f7e888a28b86184db1102ca39ff
Do you use caja-1.8.2 ?

**Comment by caz747** [comment]
Since I switched back to Mint 17 I have been using caja-1.8.1 and the problem with the white text below the icons is no longer there. It was when I was using Mint 17.1, and I assume caja-1.8.2, that the text problem was present.
I must admit I'm not really sure what is causing the problem with the white icon text on a white background with Mint 17.1. I thought it was caused by caja, but maybe it's something else.

**Comment by temcat** [comment]
This issue is still present for me in Caja 1.8.2 on Mint 17.1 32-bit.

**Comment by gadicc** [comment]
Have the same problem on caja 1.8.2-1 in ArchLinux.

* Opening an icon view folder (e.g. from Places panel menu) works fine (i.e. black text on white background)

* Opening an icon view folder from within a list folder, has this problem (i.e. white text on white background).

* A view that is working, when cycling from icon -> list -> icon, stops working.

* Changing themes will "repair" a non-working view until it breaks again (by changing to a list view and back).

To be clear, a list view displays correctly.  Compact view is broken in the same manner.

So it seems the list view is immutably setting some variable, or setting a variable that override the default behaviour used in icon view.

**Comment by caz747** [comment]
The problem is no longer present for me. I upgraded to Mint 17.1 and this time the text below the icons was black as it should be. I have no idea why I had this problem first time round when I installed 17.1.

I'm running caja 1.8.2, Mint 17.1, 64-bit.

I did install all the gtx engines that the theme I use requires.

A tip I heard on the Mint forum for anyone with a similar problem was to open up caja, click on Edit, Background and Emblems, then click on the Reset tile and drag it onto the page. Apparently, for some, this restores the black text.

**Comment by gadicc** [comment]
> A tip I heard on the Mint forum for anyone with a similar problem was to open up caja, click on Edit, Background and Emblems, then click on the Reset tile and drag it onto the page. Apparently, for some, this restores the black text.

Whoa, @caz747, nice one!  That totally solved the problem for me :)  Permanently.  I imagine it's still worth hunting this down though.

**Comment by NiceandGently** [comment]
@monsta 
looks like this report can be closed

**Comment by NiceandGently** [comment]
@monsta 
looks like this report can be closed

**Comment by Shelagh-Lewins** [comment]
The problem is not fixed, it's still there in Mint 17.3. The workaround solved the problem for me but it ought to be fixed instead of expecting all users to find this post.
