### ISSUE TITLE
Caja help not found.

### ISSUE THREAD

**Issue by lahtis** [mate-desktop/caja#403]
Press F1 funktion button to open F1 Contents (help).

The document does not exist
Location "help:mate-user-guide/goscaja-1" does not control the right side

im using Finnish language pack. My version Caja is 1.8.2

**Comment by nicekiwi** [comment]
Confirmed with English language pack too.

**Comment by ZrN-kAyDqY** [comment]
Is it due to the issue mentioned by M. Wimpress at this link?

https://bugs.launchpad.net/ubuntu-mate/+bug/1392502

**Comment by monsta** [comment]
Yes, once mate-user-guide is ready and all MATE apps make use of it, this issue should be resolved.
As @flexiondotorg stated in that LP bug report, this is the only item left in [the roadmap](http://wiki.mate-desktop.org/roadmap) for 1.10.

**Comment by ZrN-kAyDqY** [comment]
Thanks!

**Comment by dcharlespyle** [comment]
I just installed mate-user-guide from koji in Fedora 22 and still get the same errors about missing pages.

**Comment by monsta** [comment]
Yes, m-u-g is incomplete at the moment. We decided to release it as 1.10.0 because we couldn't wait any longer (it was the only roadmap item holding us from release).
We'll try to update it later.

**Comment by monsta** [comment]
Original issue fixed in https://github.com/mate-desktop/caja/commit/d01fbc6c9921253bb023d3e40bd763f4a931e840.
Issue for dialogs is worked around in https://github.com/mate-desktop/caja/commit/b4e25754bf17ef54569367718eda57ea759108c5. You'll get to the main page instead of getting error message, I think it's an improvement already. :)

When m-u-g will be complete, we'll show the corresponding help page in every dialog.

**Comment by monsta** [comment]
Oh, and that will work only after https://github.com/mate-desktop/mate-user-guide/pull/3 is merged (or, if you don't want to wait, you can pick that commit yourself and rebuild m-u-g).

**Comment by flexiondotorg** [comment]
https://github.com/mate-desktop/mate-user-guide/pull/3 is merged.
