### ISSUE TITLE
Unmounting and notification about unmounting

### ISSUE THREAD

**Issue by zaps166** [mate-desktop/caja#491]
When device is in unmounting state, Caja doesn't provide any information about it. For example on Thunar we have simple notification: ![notification](https://cloud.githubusercontent.com/assets/6239090/12034977/23b057d4-ae38-11e5-93eb-690b19d5480a.png).

It will be fine if Caja will provide two positions: Unmount and Eject like in Thunar. Currently only Eject is on the list.

**Comment by e-M-c-E** [comment]
I workaround this by using CairoDock, which have notifications about mounting and unmounting some device - for example the mobile phone.

**Comment by zaps166** [comment]
Hmm, but it will be nice to have this in Caja especially for users which don't know when they may have to disconnect the device...
And the Unmount option in popup menu will also be very useful (now you must write the 'umount' command. Sometimes you want to unmount only (not eject the device)).

**Comment by raveit65** [comment]
Hmm, i see a eject button and the device is mounted.
If not i don't see a eject button.
Very hard to make it more clear.
And in the right click menu the ejcect command is grey out if not mounted.
I do not really understand what can be confusing.
Maybe your theme have issues?

**Comment by zaps166** [comment]
My previous comment wasn't clear, so I'll explain it better.

```
And in the right click menu the eject command is grey out if not mounted.
```
There is possibility to eject the device if it is not mounted, so I can do it on my USB-Stick (it is good to me).

I meant about additional menu entry: "Unmount" as a feature request (not a bug). It will only unmount the partition without trying to eject the device :) Otherwise I (or other users) must write the 'sudo umount /dev/something' command to *not* eject the device. Ejected devices can be unplugged only, so re-mounting is not possible in most cases (btw. some devices can't eject, so I think that in this case it will unmount only).

And the second feature request (this is about the first sentence in my previous comment) is about the unmounting-state notification (see the Thunar notification (I don't know the English name of this feature :D): ![notification](https://cloud.githubusercontent.com/assets/6239090/12034977/23b057d4-ae38-11e5-93eb-690b19d5480a.png)). Showing this animated "thing" while unmounting is fine, because unmounting can take long time to finish, so it is good to know the state without watching I/O waits or the LED on the device (not all devices have a notification LED) :)

**Comment by e-M-c-E** [comment]
The most problems with mounting/unmounting/ejecting are for example with the MTP enabled devices and zero-config modems (those with "embedded" cd-drive with win-installation files)

**Comment by denispr** [comment]
I agree with zaps166, unmounting can sometimes take a long time and it would be nice to get a desktop notification when it is finished.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/pull/667 was merged some time ago, and provides notification when devices are safe to unplug. The code was ported over from Nemo, and is in caja 1.17 from git master.

**Comment by luquino** [comment]
Hi!
I'm affected from the issue described in this thread and I see that has been fixed in Caja 1.17.
I'm using Mate on Ubuntu 16.04, my actual version of Caja is 1.12.7 . Can I upgrade to Caja 1.17?
How can I do it?
Many thanks for your help.

**Comment by Martina-Neumayer** [comment]
@luquino Hi, I have Caja v.1.18.3 and this issue is still there.

**Comment by luquino** [comment]
O.o Really? :-(

**Comment by Martina-Neumayer** [comment]
@luquino Sadly yes. I am thinking about to change my DE from Mate to something else, because of those bugs. Not only this one, but mostly due tho the nasty "freeze-by-moving-files" one.
For me Caja in this state is simply unusable.

**Comment by luquino** [comment]
I'm sorry you say that, actually for me Mate is very good and I don't find many problems.
I don't know which is the the problem in moving files, I frequently do that operation but I never got any freeze, maybe your problem is related to some not perfect integration of Caja with your hardware.
Anyway there are no other DE like Mate, I looked for it long time, you will have to change many things.

**Comment by Martina-Neumayer** [comment]
@luquino Nope, is not an hardware problem. There is somwhere here on the git an big topic about this issue.

**Comment by Martina-Neumayer** [comment]
@luquino Ok, I found it.. Look at the issue #380
