### ISSUE TITLE
[Feature request] Make Caja calculate folder size in same units as file size

### ISSUE THREAD

**Issue by jbn-github** [mate-desktop/caja#798]
#### Expected behaviour
I expected Caja to show me folders in the same units as files -- human-readable size values in KB, MB, GB, TB, and so on.

#### Actual behaviour
Folders show up in a size unit of items inside the folder which is useless for determining which item in a folder uses up the most space on the volume.

I understand that implementing this will generate a lot of disk/network access and that's okay. I'd like to have the option to do this because I'd like to have an always-updated view of which folders occupy a lot of space. I'd like to get this information without another program (such as K4DirState) or running `du --summarize --human-readable * |sort -hr |less` on the command line to get a list of items in the current working directory sorted by their size (largest -> smallest).

I suggest this be a togglable feature set to off by default, much as it is in MacOS's Finder. I'd like it if one could turn this on in Caja, wait while Caja computes the size of folders in the opened Caja windows, and lets users sort by size in a more meaningful way (no more using radically different units for folders than files).

#### Steps to reproduce the behaviour
Open a folder with Caja that has both folders (with something in the subfolder) and files in the folder. Switch to details/list view and (if necessary) add the size column.

#### MATE general version
1.16.6

#### Package version
$ apt list --installed caja
Listing... Done
caja/stable,now 1.16.6-1 amd64 [installed,automatic]

#### Linux Distribution
From Debian GNU/Linux 9.0:
$ cat /etc/debian_version 
9.0

**Comment by lukefromdc** [comment]
Until https://github.com/mate-desktop/caja/issues/380#issuecomment-309853091 has been fixed, anything that causes Caja to generate more disk accesses might be a bad idea, and thus would require an option to turn it off when users get trouble from it.

**Comment by allanlaal** [comment]
#380 has been closed

this feature is sorely needed! (still missing in 1.24.0)

**Comment by UKTomperry** [comment]
Bump! Please can we have this features added (sorry to drag this back up, but I'd like to chase this up). Or, at least a Caja extension. 

Yes, this would generate a lot of disk activity, but that's exactly why the OP wants it to be an option you can toggle. 

How it's done in MacOs (actually going back to MacOS system 7) is that each directory size is computed at idle, one after the other, in the background. If the window is closed, the background task / subfolder size calculation is halted.

Please can we have this option, or even a plug-in to allow this option.
